"""
services/pdf_generator_service.py
Generates a formatted downloadable PDF from a RAG answer.
Requires: reportlab (pip install reportlab)
"""

import os, uuid, datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY

_BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_PDF_DIR  = os.path.join(_BASE_DIR, "data", "generated_pdfs")
os.makedirs(_PDF_DIR, exist_ok=True)


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("T", parent=base["Heading1"], fontSize=16,
            textColor=colors.HexColor("#1D4ED8"), spaceAfter=4, alignment=TA_CENTER),
        "sub":   ParagraphStyle("S", parent=base["Normal"], fontSize=10,
            textColor=colors.HexColor("#64748B"), spaceAfter=12, alignment=TA_CENTER),
        "h2":    ParagraphStyle("H2", parent=base["Heading2"], fontSize=12,
            textColor=colors.HexColor("#1E3A5F"), spaceAfter=4, spaceBefore=10),
        "body":  ParagraphStyle("B", parent=base["Normal"], fontSize=10,
            leading=14, spaceAfter=6, alignment=TA_JUSTIFY),
        "small": ParagraphStyle("SM", parent=base["Normal"], fontSize=8,
            textColor=colors.HexColor("#64748B"), spaceAfter=3, leftIndent=10),
        "foot":  ParagraphStyle("F", parent=base["Normal"], fontSize=8,
            textColor=colors.HexColor("#94A3B8"), alignment=TA_CENTER),
    }


def _esc(t: str) -> str:
    return t.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;")


def generate_syllabus_pdf(query: str, answer: str,
                           sources: list, chunks: list = None) -> dict:
    """Build and save a formatted PDF. Returns dict with download_url."""
    uid      = uuid.uuid4().hex[:8]
    filename = f"syllabus_{uid}.pdf"
    filepath = os.path.join(_PDF_DIR, filename)
    s        = _styles()
    story    = []

    story.append(Paragraph("EduBot — College Information Assistant", s["title"]))
    story.append(Paragraph(
        datetime.datetime.now().strftime("Generated on %B %d, %Y  %H:%M"), s["sub"]))
    story.append(HRFlowable(width="100%", thickness=1.5,
                             color=colors.HexColor("#2563EB"), spaceAfter=12))

    story.append(Paragraph("Your Question", s["h2"]))
    story.append(Paragraph(_esc(query), s["body"]))
    story.append(Spacer(1, 0.3*cm))

    story.append(HRFlowable(width="100%", thickness=0.5,
                             color=colors.HexColor("#E2E8F0"), spaceAfter=6))
    story.append(Paragraph("Answer", s["h2"]))
    for line in answer.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 0.15*cm))
            continue
        if line.startswith(("•","-","*")):
            line = "\u2022 " + line.lstrip("•-* ")
        story.append(Paragraph(_esc(line), s["body"]))

    if sources:
        story.append(Spacer(1, 0.3*cm))
        story.append(HRFlowable(width="100%", thickness=0.5,
                                 color=colors.HexColor("#E2E8F0"), spaceAfter=6))
        story.append(Paragraph("Source Documents", s["h2"]))
        for src in sources:
            story.append(Paragraph(f"\u2022 {_esc(src)}", s["small"]))

    if chunks:
        story.append(Spacer(1, 0.3*cm))
        story.append(HRFlowable(width="100%", thickness=0.5,
                                 color=colors.HexColor("#E2E8F0"), spaceAfter=6))
        story.append(Paragraph("Reference Excerpts", s["h2"]))
        for i, c in enumerate(chunks[:3], 1):
            src  = c.metadata.get("source","Unknown") if hasattr(c,"metadata") else "—"
            text = c.page_content if hasattr(c,"page_content") else str(c)
            story.append(Paragraph(f"Excerpt {i} — {_esc(src)}", s["small"]))
            story.append(Paragraph(_esc(text[:500]+("…" if len(text)>500 else "")), s["small"]))
            story.append(Spacer(1, 0.15*cm))

    story.append(Spacer(1, 0.8*cm))
    story.append(HRFlowable(width="100%", thickness=0.5,
                             color=colors.HexColor("#E2E8F0"), spaceAfter=6))
    story.append(Paragraph(
        "Auto-generated by EduBot. For official details refer to the college registrar.",
        s["foot"]))

    SimpleDocTemplate(filepath, pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm,
        topMargin=2*cm,  bottomMargin=2*cm).build(story)

    kb = round(os.path.getsize(filepath)/1024, 1)
    print(f"[PDFGen] {filename} ({kb} KB)")
    return {"filename": filename, "file_path": filepath,
            "download_url": f"/downloads/{filename}", "size_kb": kb}


def cleanup_old_pdfs(max_age_hours: int = 24) -> int:
    import time
    now, deleted = time.time(), 0
    for f in os.listdir(_PDF_DIR):
        fp = os.path.join(_PDF_DIR, f)
        if os.path.isfile(fp) and (now - os.path.getmtime(fp)) > max_age_hours*3600:
            os.remove(fp); deleted += 1
    if deleted:
        print(f"[PDFGen] Cleaned {deleted} old PDF(s).")
    return deleted
